spring:
  output:
    ansi:
      enabled: always
  datasource:
    url: jdbc:mysql://localhost:3306/jpabook?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: mysql
    driver-class-name=com: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
#        show_sql: true
        format_sql: true
logging:
  level:
    org.hibernate.SQL: debug